# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Siyuan Zhang
title: Software Development Engineer
email: jason4huare@gmail.com
website: https://github.com/Jasonzzzz28

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: Jasonzzzz28
linkedin_username: siyuan-zhang-8784a8153

# Additional icon links
additional_links:
- title: GitHub Profile
  icon: fab fa-github
  url: https://github.com/Jasonzzzz28

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Siyuan Zhang, and I'm a passionate software engineer with a strong background in backend development, distributed systems, and machine learning. I have worked with leading companies like PayPal, contributing to critical projects in credit acquisition systems and microservices architecture.

  I am most skilled in: <mark>Java</mark>, <mark>Python</mark>, and <mark>Spring Framework</mark>.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: New York University
        caption: 2024 - Present
        sub_title: M.S. Computer Engineering
        quote: >
          Deepening expertise in computer engineering, focusing on machine learning systems and distributed architecture.
        description: | # this will include new lines to allow paragraphs
          Currently pursuing a Master’s degree with a focus on computer engineering, enhancing skills in system design and data-driven applications.

      - layout: left
        title: University of Maryland at College Park
        caption: 2017 - 2021
        sub_title: B.S. Computer Science, Minor in Statistics
        quote: >
          Building a solid foundation in computer science and statistical analysis.
        description: | # this will include new lines to allow paragraphs
          Graduated with a 3.7 GPA and Dean’s List recognition, completing coursework in algorithms, machine learning, and distributed systems.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: PayPal
        link: paypal.com
        sub_title: Software Engineer
        caption: July 2021 - March 2024
        quote: >
          Building reliable and efficient systems for seamless credit acquisition and notification processing.
        description: | # this will include new lines to allow paragraphs
          Worked on the Credit Acquisition BNPL (Buy Now Pay Later) Team as a backend software engineer. Developed and maintained async processing systems for credit application results using AMQ messaging and batch processing, reducing unprocessed applications by 70%. Implemented JSON Web Token-based authorization for internal APIs and built a microservice for processing cloud events with Spring Boot.

      - layout: left
        title: PayPal
        link: paypal.com
        sub_title: Software Engineer Intern
        caption: June 2020 - August 2020
        quote: >
          Innovating fraud detection and system failure remediation for PayPal and Venmo credit accounts.
        description: | # this will include new lines to allow paragraphs
          Developed microservice features to automate handling of fraud cases and account lifecycle service failures. Automated system failure remediation, saving 4+ hours per failure case, and implemented Jenkins CI/CD pipelines for build and deployment.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Racetrack AI
        link: github.com/Jasonzzzz28
        additional_links:
          - title: Racetrack AI GitHub Repository
            icon: fab fa-github
            url: https://github.com/Jasonzzzz28
        quote: >
          A Python AI application that utilizes multiple search algorithms with self-designed and optimized heuristic functions for the Racetrack game.
        description: | # this will include new lines to allow paragraphs
          Developed an AI-based solution for the Racetrack game, focusing on performance optimization and decision-making strategies. This project helped me refine my skills in search algorithms and heuristic evaluation.

      - layout: top-middle
        title: Cache-Augmented GraphRAG
        link: github.com/Jasonzzzz28
        additional_links:
          - title: Cache-Augmented GraphRAG GitHub Repository
            icon: fab fa-github
            url: https://github.com/Jasonzzzz28
        quote: >
          A hybrid Retrieval-Augmented Generation (RAG) framework integrating adaptive caching and graph-based indexing.
        description: | # this will include new lines to allow paragraphs
          This project improved retrieval efficiency, reduced latency, and enhanced contextual coherence for Large Language Models (LLMs).

      - layout: top-middle
        title: Geolocation Database
        link: github.com/Jasonzzzz28
        additional_links:
          - title: Geolocation Database GitHub Repository
            icon: fab fa-github
            url: https://github.com/Jasonzzzz28
        quote: >
          A Java-based database of 2D map locations using self-designed data structures.
        description: | # this will include new lines to allow paragraphs
          Implemented an Extended Scapegoat Tree and Extended Self-balancing K-d Tree for efficient querying of geospatial data.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my passion for software engineering, some of my other interests include:
      - Badminton
      - Movies
      - Traveling
      - [Contributing to open-source projects](https://github.com/Jasonzzzz28)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag